-- begin DISKEXCHANGE_TAKEN_ITEM
alter table DISKEXCHANGE_TAKEN_ITEM add constraint FK_DISKEXCHANGE_TAKEN_ITEM_ON_DISK foreign key (DISK_ID) references DISKEXCHANGE_DISK(ID)^
alter table DISKEXCHANGE_TAKEN_ITEM add constraint FK_DISKEXCHANGE_TAKEN_ITEM_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_DISKEXCHANGE_TAKEN_ITEM_ON_DISK on DISKEXCHANGE_TAKEN_ITEM (DISK_ID)^
create index IDX_DISKEXCHANGE_TAKEN_ITEM_ON_USER on DISKEXCHANGE_TAKEN_ITEM (USER_ID)^
-- end DISKEXCHANGE_TAKEN_ITEM
-- begin DISKEXCHANGE_DISK
alter table DISKEXCHANGE_DISK add constraint FK_DISKEXCHANGE_DISK_ON_OWNER foreign key (OWNER_ID) references SEC_USER(ID)^
create index IDX_DISKEXCHANGE_DISK_ON_OWNER on DISKEXCHANGE_DISK (OWNER_ID)^
-- end DISKEXCHANGE_DISK
